name: s3_dart_lite
description: A lightweight S3 client for Dart, ported from the excellent TypeScript s3-lite-client (https://github.com/bradenmacdonald/s3-lite-client).
version: 0.0.1
repository: https://github.com/pheonixeye/s3-dart-lite.git

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  crypto: ^3.0.7
  http: ^1.6.0
  path: ^1.9.1
  xml: ^6.6.1
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
