name: s3_dart_lite
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  crypto: ^3.0.7
  http: ^1.6.0
  path: ^1.9.1
  xml: ^6.6.1
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
